### ISSUE TITLE
Call to a member function format() on string

### ISSUE THREAD

**Issue by hcivelek** [payconn/nestpay#24]
This error points line 32 at src/Nestpay/Request/PurchaseRequest.php 

`$body->addChild('Expires', $model->getCreditCard()->getExpireMonth()->format('m').'/'.$model->getCreditCard()->getExpireYear()->format('y'));`

**Comment by muratsac** [comment]
@hcivelek thank you for feedback. I will fix.

**Comment by crx4** [comment]
I am having the same error on PHP 7.4.
