### ISSUE TITLE
Release v.1.1.11 tag is not in proper format

### ISSUE THREAD

**Issue by ahmett** [payconn/nestpay#29]
Hi @muratsac,
I notice that there is a little typo on release tag `v.1.1.11`, it needs to be `v1.1.11` can you update this ? So packagist be able to update the package to latest version.

**Comment by muratsac** [comment]
Hi @ahmett , 

Thank you for information. 

I fixed. Can you check?

**Comment by ahmett** [comment]
Now it's working correctly, thanks!
